application:
    resource: "@SomeBundle/Resources/config/routing.yml"
    prefix:   /app

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
