<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8tuxzxm\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8tuxzxm/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/Container8tuxzxm.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\Container8tuxzxm\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \Container8tuxzxm\appProdDebugProjectContainer(array(
    'container.build_hash' => '8tuxzxm',
    'container.build_id' => '9f240dd7',
    'container.build_time' => 1525363241,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8tuxzxm');
