<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGgxxnb7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGgxxnb7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGgxxnb7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGgxxnb7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGgxxnb7\appProdProjectContainer(array(
    'container.build_hash' => 'Ggxxnb7',
    'container.build_id' => '12efb27c',
    'container.build_time' => 1525361837,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGgxxnb7');
