<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Form/Extension/DocumentationExtension.php';

return $this->services['Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension'] = new \Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension();
