<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLl7nr7s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLl7nr7s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLl7nr7s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLl7nr7s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLl7nr7s\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ll7nr7s',
    'container.build_id' => 'ac965c18',
    'container.build_time' => 1525360232,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLl7nr7s');
